title: "InstAL"
author: "InstAL"
description: "Made with <a href='https://github.com/niklasbuschmann/contrast'>contrast</a>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "gdpr.md"}
  - {file: "index.md"}
  - {file: "guide.md"}
  - {file: "people.md"}
  - {file: "publications.md"}
  - {file: "downloads.md"}

external:                  
  - {title: Github, icon: github, url: "https://github.com/instsuite/instal-stable"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
